"""empty message

Revision ID: 833b191c178a
Revises: 
Create Date: 2019-12-20 17:19:37.620892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833b191c178a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_artist_id_key', 'show', type_='unique')
    op.drop_constraint('show_venue_id_key', 'show', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('show_venue_id_key', 'show', ['venue_id'])
    op.create_unique_constraint('show_artist_id_key', 'show', ['artist_id'])
    # ### end Alembic commands ###
